package com.alibaba.idst.nlsdemo;

import android.util.Log;

import java.io.IOException;
import java.util.HashMap;

import okhttp3.OkHttpClient;
import okhttp3.Request;

/**
 * Created by Administrator on 2018/3/2.
 */

public class Expressage{


    /**
     * https://market.aliyun.com/products/56928004/cmapi023201.html?spm=5176.730005.0.0.2L4ktL#sku=yuncode1720100000
     * 阿里云api市场上寻找合适的api
     */


    public static HashMap<String,String> companyData = new HashMap();

    public  static String gxali(String n,String t) throws IOException {

        try {
            String url = ApiConstants.EXPRESSAGE_API_URL+"?n="+n+"&t="+t;
            Log.i("info", url);
            OkHttpClient client = new OkHttpClient();
            Request request = new Request.Builder().url(url)
                    .addHeader("Authorization" ,"APPCODE " + ApiConstants.EXPRESSAGE_API_CODE)
                    .build();
            okhttp3.Response response = client.newCall(request).execute();

            if (response.isSuccessful()) {
                String result = response.body().string();
                Log.i("result", result);
                return result;
            } else {
                Log.i("error", "okHttp is request error");
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
        return "查询失败";
    }

    static {
        companyData.put("顺丰","SF");
        companyData.put("百世快递","HTKY");
        companyData.put("中通","ZTO");
        companyData.put("申通","STO");
        companyData.put("圆通","YTO");
        companyData.put("韵达","YD");
        companyData.put("邮政平邮","YZPY");
        companyData.put("EMS","EMS");
        companyData.put("天天","HHTT");
        companyData.put("京东","JD");
        companyData.put("全峰","QFKD");
        companyData.put("国通","GTO");
        companyData.put("优速","UC");
        companyData.put("德邦","DBL");
        companyData.put("快捷","FAST");
        companyData.put("亚马逊","AMAZON");
        companyData.put("宅急送","ZJS");
        companyData.put("安捷快递","AJ");
        companyData.put("亚马逊物流","AMAZON");
        companyData.put("澳门邮政","AOMENYZ");
        companyData.put("安能物流","ANE");
        companyData.put("安信达快递","AXD");
        companyData.put("澳邮专线","AYCA");
        companyData.put("八达通","BDT");
        companyData.put("百福东方","BFDF");
        companyData.put("贝海国际","BHGJ");
        companyData.put("北青小红帽","BQXHM");
        companyData.put("百世快运","BTWL");
        companyData.put("CCES快递","CCES");
        companyData.put("程光","CG");
        companyData.put("城市100","CITY100");
        companyData.put("城际快递","CJKD");
        companyData.put("CNPEX中邮快递","CNPEX");
        companyData.put("COE东方快递","COE");
        companyData.put("长沙创一","CSCY");
        companyData.put("成都善途速运","CDSTKY");
        companyData.put("联合运通","CTG");
        companyData.put("德邦","DBL");
        companyData.put("D速物流","DSWL");
        companyData.put("递四方速递","D4PX");
        companyData.put("大田物流","DTWL");
        companyData.put("EWE","EWE");
        companyData.put("EMS","EMS");
        companyData.put("快捷速递","FAST");
        companyData.put("FEDEX联邦(国内件）","FEDEX");
        companyData.put("FEDEX联邦(国际件）","FEDEX_GJ");
        companyData.put("飞康达","FKD");
        companyData.put("富腾达","FTD");
        companyData.put("冠达","GD");
        companyData.put("广东邮政","GDEMS");
        companyData.put("共速达","GSD");
        companyData.put("国通快递","GTO");
        companyData.put("广通","GTONG");
        companyData.put("高铁速递","GTSD");
        companyData.put("汇丰物流","HFWL");
        companyData.put("黑狗冷链","HGLL");
        companyData.put("天天快递","HHTT");
        companyData.put("恒路物流","HLWL");
        companyData.put("天地华宇","HOAU");
        companyData.put("鸿桥供应链","HOTSCM");
        companyData.put("海派通物流公司","HPTEX");
        companyData.put("华强物流","hq568");
        companyData.put("环球速运","HQSY");
        companyData.put("百世快递","HTKY");
        companyData.put("华夏龙物流","HXLWL");
        companyData.put("豪翔物流","HXWL");
        companyData.put("好来运快递","HYLSD");
        companyData.put("捷安达","JAD");
        companyData.put("京东","JD");
        companyData.put("京广速递","JGSD");
        companyData.put("九曳供应链","JIUYE");
        companyData.put("佳吉快运","JJKY");
        companyData.put("嘉里物流","JLDT");
        companyData.put("捷特快递","JTKD");
        companyData.put("急先达","JXD");
        companyData.put("晋越快递","JYKD");
        companyData.put("加运美","JYM");
        companyData.put("景光物流","JGWL");
        companyData.put("佳怡物流","JYWL");
        companyData.put("跨越速运","KYSY");
        companyData.put("龙邦快递","LB");
        companyData.put("联昊通速递","LHT");
        companyData.put("民邦快递","MB");
        companyData.put("民航快递","MHKD");
        companyData.put("美快","MK");
        companyData.put("明亮物流","MLWL");
        companyData.put("南方","NF");
        companyData.put("能达速递","NEDA");
        companyData.put("平安达腾飞快递","PADTF");
        companyData.put("泛捷快递","PANEX");
        companyData.put("品骏","PJ");
        companyData.put("PCA Express","PCA");
        companyData.put("全晨快递","QCKD");
        companyData.put("全峰快递","QFKD");
        companyData.put("全日通快递","QRT");
        companyData.put("全信通","QXT");
        companyData.put("瑞丰速递","RFEX");
        companyData.put("如风达","RFD");
        companyData.put("瑞丰速递","RFEX");
        companyData.put("赛澳递","SAD");
        companyData.put("圣安物流","SAWL");
        companyData.put("盛邦物流","SBWL");
        companyData.put("上大物流","SDWL");
        companyData.put("顺丰快递","SF");
        companyData.put("盛丰物流","SFWL");
        companyData.put("盛辉物流","SHWL");
        companyData.put("速通物流","ST");
        companyData.put("速腾快递","STWL");
        companyData.put("速必达物流","SUBIDA");
        companyData.put("速递e站","SDEZ");
        companyData.put("速尔快递","SURE");
        companyData.put("天天","HHTT");
        companyData.put("台湾邮政","TAIWANYZ");
        companyData.put("全一快递","UAPEX");
        companyData.put("UEQ Express","UEQ");
        companyData.put("优速快递","UC");
        companyData.put("万家康","WJK");
        companyData.put("万家物流","WJWL");
        companyData.put("万象物流","WXWL");
        companyData.put("新邦物流","XBWL");
        companyData.put("迅驰物流","XCWL");
        companyData.put("信丰快递","XFEX");
        companyData.put("希优特","XYT");
        companyData.put("新杰物流","XJ");
        companyData.put("源安达快递","YADEX");
        companyData.put("远成物流","YCWL");
        companyData.put("韵达快递","YD");
        companyData.put("义达国际物流","YDH");
        companyData.put("易达通","YDT");
        companyData.put("越丰物流","YFEX");
        companyData.put("原飞航物流","YFHEX");
        companyData.put("亚风快递","YFSD");
        companyData.put("运通快递","YTKD");
        companyData.put("圆通速递","YTO");
        companyData.put("亿翔快递","YXKD");
        companyData.put("运东西","YUNDX");
        companyData.put("邮政平邮/小包","YZPY");
        companyData.put("增益快递","ZENY");
        companyData.put("汇强快递","ZHQKD");
        companyData.put("宅急送","ZJS");
        companyData.put("众通快递","ZTE");
        companyData.put("中铁快运","ZTKY");
        companyData.put("中通速递","ZTO");
        companyData.put("中铁物流","ZTWL");
        companyData.put("中邮物流","ZYWL");
        companyData.put("AAE全球专递","AAE");
        companyData.put("ACS雅仕快递","ACS");
        companyData.put("ADP Express Tracking","ADP");
        companyData.put("安圭拉邮政","ANGUILAYOU");
        companyData.put("APAC","APAC");
        companyData.put("Aramex","ARAMEX");
        companyData.put("奥地利邮政","AT");
        companyData.put("Australia Post Tracking","AUSTRALIA");
        companyData.put("比利时邮政","BEL");
        companyData.put("BHT快递","BHT");
        companyData.put("秘鲁邮政","BILUYOUZHE");
        companyData.put("巴西邮政","BR");
        companyData.put("不丹邮政","BUDANYOUZH");
        companyData.put("加拿大邮政","CA");
        companyData.put("DHL","DHL");
        companyData.put("DHL(英文版)","DHL_EN");
        companyData.put("DHL全球","DHL_GLB");
        companyData.put("DHL Global Mail","DHLGM");
        companyData.put("丹麦邮政","DK");
        companyData.put("DPD","DPD");
        companyData.put("DPEX","DPEX");
        companyData.put("EMS国际","EMSGJ");
        companyData.put("EShipper","ESHIPPER");
        companyData.put("国际e邮宝","GJEYB");
        companyData.put("国际邮政包裹","GJYZ");
        companyData.put("GLS","GLS");
        companyData.put("安的列斯群岛邮政","IADLSQDYZ");
        companyData.put("澳大利亚邮政","IADLYYZ");
        companyData.put("阿尔巴尼亚邮政","IAEBNYYZ");
        companyData.put("阿尔及利亚邮政","IAEJLYYZ");
        companyData.put("阿富汗邮政","IAFHYZ");
        companyData.put("安哥拉邮政","IAGLYZ");
        companyData.put("阿根廷邮政","IAGTYZ");
        companyData.put("埃及邮政","IAJYZ");
        companyData.put("阿鲁巴邮政","IALBYZ");
        companyData.put("奥兰群岛邮政","IALQDYZ");
        companyData.put("阿联酋邮政","IALYYZ");
        companyData.put("阿曼邮政","IAMYZ");
        companyData.put("阿塞拜疆邮政","IASBJYZ");
        companyData.put("埃塞俄比亚邮政","IASEBYYZ");
        companyData.put("爱沙尼亚邮政","IASNYYZ");
        companyData.put("阿森松岛邮政","IASSDYZ");
        companyData.put("博茨瓦纳邮政","IBCWNYZ");
        companyData.put("波多黎各邮政","IBDLGYZ");
        companyData.put("冰岛邮政","IBDYZ");
        companyData.put("白俄罗斯邮政","IBELSYZ");
        companyData.put("波黑邮政","IBHYZ");
        companyData.put("保加利亚邮政","IBJLYYZ");
        companyData.put("巴基斯坦邮政","IBJSTYZ");
        companyData.put("黎巴嫩邮政","IBLNYZ");
        companyData.put("便利速递","IBLSD");
        companyData.put("玻利维亚邮政","IBLWYYZ");
        companyData.put("巴林邮政","IBLYZ");
        companyData.put("百慕达邮政","IBMDYZ");
        companyData.put("波兰邮政","IBOLYZ");
        companyData.put("宝通达","IBTD");
        companyData.put("贝邮宝","IBYB");
        companyData.put("出口易","ICKY");
        companyData.put("达方物流","IDFWL");
        companyData.put("德国邮政","IDGYZ");
        companyData.put("爱尔兰邮政","IE");
        companyData.put("厄瓜多尔邮政","IEGDEYZ");
        companyData.put("俄罗斯邮政","IELSYZ");
        companyData.put("厄立特里亚邮政","IELTLYYZ");
        companyData.put("飞特物流","IFTWL");
        companyData.put("瓜德罗普岛EMS","IGDLPDEMS");
        companyData.put("瓜德罗普岛邮政","IGDLPDYZ");
        companyData.put("俄速递","IGJESD");
        companyData.put("哥伦比亚邮政","IGLBYYZ");
        companyData.put("格陵兰邮政","IGLLYZ");
        companyData.put("哥斯达黎加邮政","IGSDLJYZ");
        companyData.put("韩国邮政","IHGYZ");
        companyData.put("华翰物流","IHHWL");
        companyData.put("互联易","IHLY");
        companyData.put("哈萨克斯坦邮政","IHSKSTYZ");
        companyData.put("黑山邮政","IHSYZ");
        companyData.put("津巴布韦邮政","IJBBWYZ");
        companyData.put("吉尔吉斯斯坦邮政","IJEJSSTYZ");
        companyData.put("捷克邮政","IJKYZ");
        companyData.put("加纳邮政","IJNYZ");
        companyData.put("柬埔寨邮政","IJPZYZ");
        companyData.put("克罗地亚邮政","IKNDYYZ");
        companyData.put("肯尼亚邮政","IKNYYZ");
        companyData.put("科特迪瓦EMS","IKTDWEMS");
        companyData.put("科特迪瓦邮政","IKTDWYZ");
        companyData.put("卡塔尔邮政","IKTEYZ");
        companyData.put("利比亚邮政","ILBYYZ");
        companyData.put("林克快递","ILKKD");
        companyData.put("罗马尼亚邮政","ILMNYYZ");
        companyData.put("卢森堡邮政","ILSBYZ");
        companyData.put("拉脱维亚邮政","ILTWYYZ");
        companyData.put("立陶宛邮政","ILTWYZ");
        companyData.put("列支敦士登邮政","ILZDSDYZ");
        companyData.put("马尔代夫邮政","IMEDFYZ");
        companyData.put("摩尔多瓦邮政","IMEDWYZ");
        companyData.put("马耳他邮政","IMETYZ");
        companyData.put("孟加拉国EMS","IMJLGEMS");
        companyData.put("摩洛哥邮政","IMLGYZ");
        companyData.put("毛里求斯邮政","IMLQSYZ");
        companyData.put("马来西亚EMS","IMLXYEMS");
        companyData.put("马来西亚邮政","IMLXYYZ");
        companyData.put("马其顿邮政","IMQDYZ");
        companyData.put("马提尼克EMS","IMTNKEMS");
        companyData.put("马提尼克邮政","IMTNKYZ");
        companyData.put("墨西哥邮政","IMXGYZ");
        companyData.put("南非邮政","INFYZ");
        companyData.put("尼日利亚邮政","INRLYYZ");
        companyData.put("挪威邮政","INWYZ");
        companyData.put("葡萄牙邮政","IPTYYZ");
        companyData.put("全球快递","IQQKD");
        companyData.put("全通物流","IQTWL");
        companyData.put("苏宁","SUNING");
        companyData.put("萨尔瓦多邮政","ISEWDYZ");
        companyData.put("塞尔维亚邮政","ISEWYYZ");
        companyData.put("斯洛伐克邮政","ISLFKYZ");
        companyData.put("斯洛文尼亚邮政","ISLWNYYZ");
        companyData.put("塞内加尔邮政","ISNJEYZ");
        companyData.put("塞浦路斯邮政","ISPLSYZ");
        companyData.put("沙特阿拉伯邮政","ISTALBYZ");
        companyData.put("土耳其邮政","ITEQYZ");
        companyData.put("泰国邮政","ITGYZ");
        companyData.put("特立尼达和多巴哥EMS","ITLNDHDBGE");
        companyData.put("突尼斯邮政","ITNSYZ");
        companyData.put("坦桑尼亚邮政","ITSNYYZ");
        companyData.put("危地马拉邮政","IWDMLYZ");
        companyData.put("乌干达邮政","IWGDYZ");
        companyData.put("乌克兰EMS","IWKLEMS");
        companyData.put("乌克兰邮政","IWKLYZ");
        companyData.put("乌拉圭邮政","IWLGYZ");
        companyData.put("文莱邮政","IWLYZ");
        companyData.put("乌兹别克斯坦EMS","IWZBKSTEMS");
        companyData.put("乌兹别克斯坦邮政","IWZBKSTYZ");
        companyData.put("西班牙邮政","IXBYYZ");
        companyData.put("小飞龙物流","IXFLWL");
        companyData.put("新喀里多尼亚邮政","IXGLDNYYZ");
        companyData.put("新加坡EMS","IXJPEMS");
        companyData.put("新加坡邮政","IXJPYZ");
        companyData.put("叙利亚邮政","IXLYYZ");
        companyData.put("希腊邮政","IXLYZ");
        companyData.put("夏浦世纪","IXPSJ");
        companyData.put("夏浦物流","IXPWL");
        companyData.put("新西兰邮政","IXXLYZ");
        companyData.put("匈牙利邮政","IXYLYZ");
        companyData.put("意大利邮政","IYDLYZ");
        companyData.put("印度尼西亚邮政","IYDNXYYZ");
        companyData.put("印度邮政","IYDYZ");
        companyData.put("英国邮政","IYGYZ");
        companyData.put("伊朗邮政","IYLYZ");
        companyData.put("亚美尼亚邮政","IYMNYYZ");
        companyData.put("也门邮政","IYMYZ");
        companyData.put("越南邮政","IYNYZ");
        companyData.put("以色列邮政","IYSLYZ");
        companyData.put("易通关","IYTG");
        companyData.put("燕文物流","IYWWL");
        companyData.put("直布罗陀邮政","IZBLTYZ");
        companyData.put("智利邮政","IZLYZ");
        companyData.put("日本邮政","JP");
        companyData.put("荷兰邮政","NL");
        companyData.put("ONTRAC","ONTRAC");
        companyData.put("全球邮政","QQYZ");
        companyData.put("瑞典邮政","RDSE");
        companyData.put("瑞士邮政","SWCH");
        companyData.put("TNT快递","TNT");
        companyData.put("UPS","UPS");
        companyData.put("USPS美国邮政","USPS");
        companyData.put("日本大和运输(Yamato)","YAMA");
        companyData.put("YODEL","YODEL");
        companyData.put("约旦邮政","YUEDANYOUZ");
        companyData.put("AOL（澳通）","AOL");
        companyData.put("BCWELT","BCWELT");
        companyData.put("笨鸟国际","BN");
        companyData.put("COE快递","COE");
        companyData.put("UEX","UEX");
        companyData.put("爱购转运","ZY_AG");
        companyData.put("爱欧洲","ZY_AOZ");
        companyData.put("澳世速递","ZY_AUSE");
        companyData.put("AXO","ZY_AXO");
        companyData.put("澳转运","ZY_AZY");
        companyData.put("八达网","ZY_BDA");
        companyData.put("蜜蜂速递","ZY_BEE");
        companyData.put("贝海速递","ZY_BH");
        companyData.put("百利快递","ZY_BL");
        companyData.put("斑马物流","ZY_BM");
        companyData.put("败欧洲","ZY_BOZ");
        companyData.put("百通物流","ZY_BT");
        companyData.put("贝易购","ZY_BYECO");
        companyData.put("策马转运","ZY_CM");
        companyData.put("赤兔马转运","ZY_CTM");
        companyData.put("CUL中美速递","ZY_CUL");
        companyData.put("德国海淘之家","ZY_DGHT");
        companyData.put("德运网","ZY_DYW");
        companyData.put("EFS POST","ZY_EFS");
        companyData.put("宜送转运","ZY_ESONG");
        companyData.put("ETD","ZY_ETD");
        companyData.put("飞碟快递","ZY_FD");
        companyData.put("飞鸽快递","ZY_FG");
        companyData.put("风雷速递","ZY_FLSD");
        companyData.put("风行快递","ZY_FX");
        companyData.put("风行速递","ZY_FXSD");
        companyData.put("飞洋快递","ZY_FY");
        companyData.put("皓晨快递","ZY_HC");
        companyData.put("皓晨优递","ZY_HCYD");
        companyData.put("海带宝","ZY_HDB");
        companyData.put("汇丰美中速递","ZY_HFMZ");
        companyData.put("豪杰速递","ZY_HJSD");
        companyData.put("360hitao转运","ZY_HTAO");
        companyData.put("海淘村","ZY_HTCUN");
        companyData.put("365海淘客","ZY_HTKE");
        companyData.put("华通快运","ZY_HTONG");
        companyData.put("海星桥快递","ZY_HXKD");
        companyData.put("华兴速运","ZY_HXSY");
        companyData.put("海悦速递","ZY_HYSD");
        companyData.put("LogisticsY","ZY_IHERB");
        companyData.put("君安快递","ZY_JA");
        companyData.put("时代转运","ZY_JD");
        companyData.put("骏达快递","ZY_JDKD");
        companyData.put("骏达转运","ZY_JDZY");
        companyData.put("久禾快递","ZY_JH");
        companyData.put("金海淘","ZY_JHT");
        companyData.put("联邦转运FedRoad","ZY_LBZY");
        companyData.put("领跑者快递","ZY_LPZ");
        companyData.put("龙象快递","ZY_LX");
        companyData.put("量子物流","ZY_LZWL");
        companyData.put("明邦转运","ZY_MBZY");
        companyData.put("美国转运","ZY_MGZY");
        companyData.put("美嘉快递","ZY_MJ");
        companyData.put("美速通","ZY_MST");
        companyData.put("美西转运","ZY_MXZY");
        companyData.put("168 美中快递","ZY_MZ");
        companyData.put("欧e捷","ZY_OEJ");
        companyData.put("欧洲疯","ZY_OZF");
        companyData.put("欧洲GO","ZY_OZGO");
        companyData.put("全美通","ZY_QMT");
        companyData.put("QQ-EX","ZY_QQEX");
        companyData.put("润东国际快线","ZY_RDGJ");
        companyData.put("瑞天快递","ZY_RT");
        companyData.put("瑞天速递","ZY_RTSD");
        companyData.put("SCS国际物流","ZY_SCS");
        companyData.put("速达快递","ZY_SDKD");
        companyData.put("四方转运","ZY_SFZY");
        companyData.put("SOHO苏豪国际","ZY_SOHO");
        companyData.put("Sonic-Ex速递","ZY_SONIC");
        companyData.put("上腾快递","ZY_ST");
        companyData.put("通诚美中快递","ZY_TCM");
        companyData.put("天际快递","ZY_TJ");
        companyData.put("天马转运","ZY_TM");
        companyData.put("滕牛快递","ZY_TN");
        companyData.put("TrakPak","ZY_TPAK");
        companyData.put("太平洋快递","ZY_TPY");
        companyData.put("唐三藏转运","ZY_TSZ");
        companyData.put("天天海淘","ZY_TTHT");
        companyData.put("TWC转运世界","ZY_TWC");
        companyData.put("同心快递","ZY_TX");
        companyData.put("天翼快递","ZY_TY");
        companyData.put("同舟快递","ZY_TZH");
        companyData.put("UCS合众快递","ZY_UCS");
        companyData.put("文达国际DCS","ZY_WDCS");
        companyData.put("星辰快递","ZY_XC");
        companyData.put("迅达快递","ZY_XDKD");
        companyData.put("信达速运","ZY_XDSY");
        companyData.put("先锋快递","ZY_XF");
        companyData.put("新干线快递","ZY_XGX");
        companyData.put("西邮寄","ZY_XIYJ");
        companyData.put("信捷转运","ZY_XJ");
        companyData.put("优购快递","ZY_YGKD");
        companyData.put("友家速递(UCS)","ZY_YJSD");
        companyData.put("云畔网","ZY_YPW");
        companyData.put("云骑快递","ZY_YQ");
        companyData.put("一柒物流","ZY_YQWL");
        companyData.put("优晟速递","ZY_YSSD");
        companyData.put("易送网","ZY_YSW");
        companyData.put("运淘美国","ZY_YTUSA");
        companyData.put("至诚速递","ZY_ZCSD");

    }

}
